views/about.py
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
from flask import Blueprint, render_template

about_blueprint = Blueprint('about', __name__)


@about_blueprint.route("/catalog/about")
def about():
    """Show about page."""
    return render_template("about.html")

views/auth.py
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
from flask import Blueprint, flash, make_response, request, redirect
from flask import render_template, url_for
from flask import session as login_session
from oauth2client.client import flow_from_clientsecrets
from oauth2client.client import FlowExchangeError
import views.user as user
import httplib2
import json
import requests
import random
import string


auth = Blueprint('auth', __name__)

GOOGLE_CLIENT_SECRET = "client_secret.json"
GOOGLE_CLIENT_ID = json.loads(
    open(GOOGLE_CLIENT_SECRET, "r").read())["web"]["client_id"]


@auth.route("/login")
def show_login():
    """Create anti-forgery state token."""
    state = "".join(random.choice(string.ascii_uppercase + string.digits)
                    for x in range(32))
    login_session["state"] = state
    return render_template("login.html", STATE=state)


@auth.route("/gconnect", methods=["POST"])
def gconnect():
    """Google connect."""

    # Validate state token
    if request.args.get("state") != login_session["state"]:
        response = make_response(json.dumps("Invalid state parameter."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    # Obtain authorization code
    code = request.data

    try:
        # Upgrade the authorization code into a credentials object
        oauth_flow = flow_from_clientsecrets(GOOGLE_CLIENT_SECRET, scope="")
        oauth_flow.redirect_uri = "postmessage"
        credentials = oauth_flow.step2_exchange(code)
    except FlowExchangeError:
        response = make_response(
            json.dumps("Failed to upgrade the authorization code."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    # Check that the access token is valid.
    access_token = credentials.access_token
    url = ("https://www.googleapis.com/oauth2/v1/tokeninfo?"
           "access_token={}").format(access_token)
    h = httplib2.Http()
    result = json.loads(h.request(url, "GET")[1])

    # If there was an error in the access token info, abort.
    if result.get("error") is not None:
        response = make_response(json.dumps(result.get("error")), 500)
        response.headers["Content-Type"] = "application/json"
        return response

    # Verify that the access token is used for the intended user.
    gplus_id = credentials.id_token["sub"]
    if result["user_id"] != gplus_id:
        response = make_response(
            json.dumps("Token's user ID doesn't match given user ID."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    # Verify that the access token is valid for this app.
    if result["issued_to"] != GOOGLE_CLIENT_ID:
        response = make_response(
            json.dumps("Token's client ID does not match app's."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    stored_access_token = login_session.get("access_token")
    stored_gplus_id = login_session.get("gplus_id")
    if stored_access_token is not None and gplus_id == stored_gplus_id:
        response = make_response(
            json.dumps("Current user is already connected."), 200)
        response.headers["Content-Type"] = "application/json"
        return response

    # Store the access token in the session for later use.
    login_session["access_token"] = credentials.access_token
    login_session["gplus_id"] = gplus_id

    # Get user info
    userinfo_url = "https://www.googleapis.com/oauth2/v1/userinfo"
    params = {"access_token": credentials.access_token, "alt": "json"}
    answer = requests.get(userinfo_url, params=params)

    data = answer.json()

    login_session["username"] = data["name"]
    login_session["picture"] = data["picture"]
    login_session["email"] = data["email"]

    # Add provider to login session.
    login_session["provider"] = "google"

    # See if user exists, if it doesn't make a new one.
    user_id = user.get_user_id(data["email"])
    if not user_id:
        user_id = user.create_user(login_session)
    login_session["user_id"] = user_id

    output = "<h1>Welcome, "
    output += login_session["username"]
    output += "!</h1>"
    output += '<img src="' + login_session["picture"] + '" '
    output += 'style = "width: 300px; height: 300px; border-radius: 150px; '
    output += '-webkit-border-radius: 150px; -moz-border-radius: 150px;"> '
    flash(
        "You are now logged in as {}.".format(login_session["username"]),
        "success")
    return output


@auth.route("/gdisconnect")
def gdisconnect():
    """Google disconnect."""
    # Revoke a current user's token and reset their login_session.
    # Only disconnect a connected user.
    access_token = login_session.get("access_token")
    if access_token is None:
        response = make_response(
            json.dumps("Current user not connected."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    url = "https://accounts.google.com/o/oauth2/revoke?token={}".format(
            access_token)
    h = httplib2.Http()
    result = h.request(url, "GET")[0]

    if result["status"] == "200":
        del login_session["access_token"]
        del login_session["gplus_id"]
        del login_session["username"]
        del login_session["email"]
        del login_session["picture"]
        response = make_response(json.dumps("Successfully disconnected."), 200)
        response.headers["Content-Type"] = "application/json"
        return response
    else:
        response = make_response(
            json.dumps("Failed to revoke token for given user.", 400))
        response.headers["Content-Type"] = "application/json"
        return response


@auth.route("/fbconnect", methods=["POST"])
def fbconnect():
    """Facebook connect."""
    if request.args.get("state") != login_session["state"]:
        response = make_response(json.dumps("Invalid state parameter."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    # Access token received (see access_token).
    access_token = request.data

    app_id = json.loads(open("fb_client_secrets.json", "r")
                        .read())["web"]["app_id"]
    app_secret = json.loads(
        open("fb_client_secrets.json", "r").read())["web"]["app_secret"]

    url = ("https://graph.facebook.com/oauth/access_token?"
           "grant_type=fb_exchange_token&client_id={}&client_secret={}"
           "&fb_exchange_token={}").format(app_id, app_secret, access_token)
    h = httplib2.Http()
    result = h.request(url, "GET")[1]

    # Use token to get user info from API.
    # userinfo_url = "https://graph.facebook.com/v2.8/me"
    """
    Due to the formatting for the result from the server token exchange we
    have to split the token first on commas and select the first index which
    gives us the key : value for the server access token then we split it on
    colons to pull out the actual token value and replace the remaining quotes
    with nothing so that it can be used directly in the graph api calls
    """
    token = result.split(",")[0].split(":")[1].replace('"', "")

    url = ("https://graph.facebook.com/v2.8/me?"
           "access_token={}&fields=name,id,email").format(token)
    h = httplib2.Http()
    result = h.request(url, "GET")[1]
    data = json.loads(result)
    login_session["provider"] = "facebook"
    login_session["username"] = data["name"]
    login_session["email"] = data["email"]
    login_session["facebook_id"] = data["id"]

    # The token must be stored in the login_session in order to properly
    # logout.
    login_session["access_token"] = token

    # Get user picture.
    url = ("https://graph.facebook.com/v2.8/me/picture?"
           "access_token={}&redirect=0&height=200&width=200").format(token)
    h = httplib2.Http()
    result = h.request(url, "GET")[1]
    data = json.loads(result)

    login_session["picture"] = data["data"]["url"]

    # See if user exists.
    user_id = user.get_user_id(login_session["email"])
    if not user_id:
        user_id = user.create_user(login_session)
    login_session["user_id"] = user_id

    output = "<h1>Welcome, "
    output += login_session["username"]

    output += "!</h1>"
    output += '<img src="'
    output += login_session["picture"]
    output += ' " style = "width: 300px; height: 300px;border-radius: 150px;'
    output += ' -webkit-border-radius: 150px;-moz-border-radius: 150px;"> '

    flash("Now logged in as {}.".format(login_session["username"]), "success")
    return output


@auth.route("/fbdisconnect")
def fbdisconnect():
    """Facebook disconnect."""
    facebook_id = login_session["facebook_id"]

    # The access token must me included to successfully logout.
    access_token = login_session["access_token"]
    url = "https://graph.facebook.com/{}/permissions?access_token={}".format(
            facebook_id, access_token)
    h = httplib2.Http()
    h.request(url, "DELETE")[1]
    return "You have been logged out."


@auth.route("/disconnect")
def disconnect():
    """Disconnect based on provider."""
    login_session["provider"] = "google"

    if "provider" in login_session:
        if login_session["provider"] == "google":
            gdisconnect()
            delete_key_login_session("gplus_id")
            delete_key_login_session("credentials")

        if login_session["provider"] == "facebook":
            fbdisconnect()
            del login_session["facebook_id"]

        delete_key_login_session("username")
        delete_key_login_session("email")
        delete_key_login_session("picture")
        delete_key_login_session("user_id")
        delete_key_login_session("provider")
        flash("You have successfully been logged out.", "success")
        return redirect(url_for("category.show_categories"))
    else:
        flash("You were not logged in.", "success")

templates/about.html
{% extends "base.html" %}
{% block content %}
  <h2>About</h2>
  <p>This application provides a list of items within a variety of categories 
  as well as provide a user registration and authentication system. 
  Registered users will have the ability to post, edit and delete their own 
  items.</p>
  <p>This web app is a project for the Udacity 
    <a href="https://in.udacity.com/course/full-stack-web-developer-nanodegree--nd004/" 
      target="_blank">Full Stack Web Developer Nanodegree</a>.
  </p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="Catalog App">
    <meta name="author" content="Alain Boisvert">
    <title>Catalog App</title>
    
    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" 
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" 
      integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" 
      crossorigin="anonymous">

    <!-- Others styles -->
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='styles.css') }}">
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-inverse bg-inverse navbar-expand-lg" style="background-color: #292B2C;">
      <a class="navbar-brand" href="{{url_for('category.show_categories')}}" style="color: #FFF;">Catalog App</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
                
      <div class="navbar-collapse collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('category.show_categories')}}" style="color: #FFF;">Categories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('about.about')}}" style="color: #FFF;">About</a>
          </li>
        </ul>

        <form class="form-inline my-2 my-lg-0">
          {% if 'username' not in session %}
            <a href="{{url_for('auth.show_login')}}" class="btn btn-danger">Login</a>
          {% else %}
            <a href="#" data-toggle="popover" data-trigger="focus" 
              title="Authentication" 
              data-content="{{ session['username'] }} ({{ session['email'] }})">
              <img src="{{ session['picture'] }}" class="picture">
            </a>
            <a href="{{url_for('auth.disconnect')}}" class="btn btn-danger">Logout</a>
          {% endif %}
        </form>
      </div>
    </nav>
    
    <div class="container-fluid" style="margin-top: 1rem;">
      <!-- Content here -->
      {% block content %}{% endblock %}
      
      <!-- Footer -->
      <hr>
      <p>
        <small>
          {% if 'username' in session %}
            You are currently signed in ({{ session['username'] }}, {{ session['email'] }}).
          {% else %}
            You are not currently signed in. 
            Please <a href="{{url_for('auth.show_login')}}">login</a> to be able 
            to add, update, or delete item information.
          {% endif %}
        </small>
      </p>
    </div>
    
    <script>
      $(function() {
        $('[data-toggle="popover"]').popover()
      });
    </script>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" 
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" 
      integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" 
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" 
      integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" 
      crossorigin="anonymous"></script>
  </body>
</html>

templates/categories.html
{% extends "base.html" %}
{% block content %}
  
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 1rem;">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <div class="row" style="margin-top: 12px;">
    <div class="col-auto">
      <h3>Categories</h3>

      {% if categories %}
        <div class="list-group">
          {% for c in categories %}
            <a href="{{url_for('item.show_items', category_name=c.name)}}" 
              class="list-group-item list-group-item-action {% if category and category.name == c.name %}active{% endif %}">{{ c.name }}</a>
          {% endfor %}
        </div>
      {% else %}
        <div class="alert alert-warning" role="alert">
          No Categories Found!
        </div>
      {% endif %}
    </div>
    <div class="col">
      <span class="h3">{{ items_title }}</span>

      {% if 'username' in session %}
        {% if category %}
          <a href="{{url_for('item.new_category_item', category_name=category.name)}}" class="btn btn-warning btn-sm add-button">Add Item</a>
        {% else %}
          <a href="{{url_for('item.new_item')}}" class="btn btn-warning btn-sm add-button">Add Item</a>
        {% endif %}
      {% endif %}

      {% if items %}
        <div class="list-group">
          {% for i in items %}
            <a href="{{url_for('item.show_item', category_name=i.category.name, item_title=i.title)}}"
            class="list-group-item list-group-item-action">{{ i.title }} 
              {% if not category %}<em class="text-danger">({{ i.category.name }})</em>{% endif %}</a>
          {% endfor %}
        </div>
      {% else %}
        <div class="alert alert-warning" role="alert">
          No Items Found!
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/delete_item.html
{% extends "base.html" %}
{% block content %}
  <h2>Delete Item</h2>
  <p>Are you sure you want to delete this item?</p>

  <div class="card">
    <div class="card-block">
      <h4 class="card-title">{{ item.title }}</h4>
      <p class="card-text"><strong>Description:</strong> {{ item.description }}</p>
      <p class="card-text"><strong>Category:</strong> {{ item.category.name }}</p>
      <hr style="max-width: 300px; text-align: left; margin-left: 0">
      <p class="card-text">
        <small>
          <b>Created by:</b> {{ item.user.name }} ({{ item.user.email }})<br>
          <b>Created at:</b> {{ item.created_date.strftime('%Y-%m-%d %-H:%M:%S') }} UTC<br>
          <b>Last modified at:</b> {{ item.updated_date.strftime('%Y-%m-%d %-H:%M:%S') }} UTC<br>
        </small>
      </p>
    </div>
  </div>

  <form action="{{url_for('item.delete_item', category_name = item.category.name, item_title = item.title)}}" method="POST">
    <div style="text-align: right;">
      <a href="{{url_for('item.show_item', category_name = item.category.name, item_title = item.title)}}" class="btn btn-primary">Cancel</a>
      <input type="submit" value="Delete" class="btn btn-danger">
    </div>
  </form>
{% endblock %}

templates/edit_item.html
{% extends "base.html" %}
{% block content %}
  <h2>Edit Item</h2>
  
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert" style="margin-top: 1rem;">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <div id="alert" class="alert alert-danger" role="alert" style="display: none;">
    <strong>Oups!</strong> Change a few things up and try submitting again.
  </div>

  <form name="myForm" action="{{url_for('item.edit_item', category_name = item.category.name, item_title = item.title)}}" method="POST" onsubmit="return validateForm();">
    <div class="form-group">
      <label for="title">Title *</label>
      <input name="title" type="text" size="80" class="form-control" value="{{item.title}}">
      <small id="titleHelp" class="form-text text-danger" style="display: none;">This field marked by an asterisk must be filled out.</small>
    </div>

    <div class="form-group">
      <label for="description">Description *</label>
      <textarea name="description" class="form-control" rows="6">{{ item.description }}</textarea>
      <small id="descriptionHelp" class="form-text text-danger" style="display: none;">This field marked by an asterisk must be filled out.</small>
    </div>

    <div class="form-group" style="display: none;">
      <label for="category_name">Category</label>
      <input name="category_name" id="category_name" type="text" size="80" class="form-control" value="{{item.category.name}}">
    </div>

    <div class="input-group form-group" style="margin-bottom: 0">
      <div class="input-group-btn">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Category *
        </button>
        <div class="dropdown-menu" id="category_menu">
          {% for c in categories %}
            <a class="dropdown-item {% if c.id == item.category_id %}active{% endif %}" href="#">{{ c.name }}</a>
          {% endfor %}
        </div>
      </div>
      <input id="category_text" type="text" class="form-control" aria-label="Text input with dropdown button"
        value="{{item.category.name}}">
    </div>

    <small id="categoryHelp" class="form-text text-danger" style="display: none;">This field marked by an asterisk must be filled out.</small>

    <p>
      <small>
        <b>Created by:</b> {{ item.user.name }} ({{ item.user.email }})<br>
        <b>Created at:</b> {{ item.created_date.strftime('%Y-%m-%d %-H:%M:%S') }} UTC<br>
        <b>Last modified at:</b> {{ item.updated_date.strftime('%Y-%m-%d %-H:%M:%S') }} UTC<br>
      </small>
    </p>

    <script>
      $(document).ready(function(){
        $('#category_menu a').click(function() {
          $("#category_menu a").removeClass("active")
          $(this).addClass('active'); 
          $("#category_text").val($(this).text())
          $("#category_name").val($(this).text())
        });
      });


      function validateForm() {
        var ok = true;

        var title = document.forms["myForm"]["title"].value;
        if (title == "") {
          ok = false;
          $("#titleHelp").show()
        } else {
          $("#titleHelp").hide()
        }
        
        var description = document.forms["myForm"]["description"].value;
        if (description == "") {
          ok = false;
          $("#descriptionHelp").show()
        } else {
          $("#descriptionHelp").hide()
        }
        
        var category_name = document.forms["myForm"]["category_name"].value;
        if (category_name == "") {
          ok = false;
          $("#categoryHelp").show()
        } else {
          $("#categoryHelp").hide()
        }

        if (!ok) {
          $("#alert").show()
        } else {
          $("#alert").hide()
        }

        return ok;
      }
    </script>
    
    {% if 'username' in session and session['user_id'] == item.user_id %}
      <div style="text-align: right;">
        <a href="{{url_for('item.show_item', category_name = item.category.name, item_title = item.title)}}" class="btn btn-primary">Cancel</a>
        <input type="submit" value="Save" class="btn btn-danger">
      </div>
    {% endif %}
  </form>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <!--LOAD PRE-REQUISITES FOR GOOGLE SIGN IN -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="//apis.google.com/js/platform.js?onload=start"> </script>
    <!-- END PRE-REQUISITES FOR GOOGLE SIGN IN -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" 
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" 
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" 
    crossorigin="anonymous">

    <style>
      body { margin: 10px; }
    </style>
  </head>
  <body>  

  <!-- GOOGLE PLUS SIGN IN -->
  <div id="signInButton">
    <span class="g-signin" 
          data-scope="openid email"
          data-clientid="534192602257-l8j1r97gvu47gc5pnpg2jpjm7ie0d51v.apps.googleusercontent.com"
          data-redirecturi="postmessage"
          data-accesstype="offline"
          data-cookiepolicy="single_host_origin"
          data-callback="signInCallback"
          data-approvalprompt="force">
    </span>
  </div>

  <div id="result"></div>

  <script>
    function signInCallback(authResult) {
      if (authResult["code"]) {
        // Hide the sign-in button now that the user is authorized
        $("#signinButton").attr("style", "display: none");

        // Send the one-time-use code to the server, if the server responds, 
        // write a "login successful" message to the web page and then redirect 
        // back to the main catalog page
        $.ajax({
          type: "POST",
          url: "/gconnect?state={{STATE}}",
          processData: false,
          data: authResult["code"],
          contentType: "application/octet-stream; charset=utf-8",
          success: function(result) {
            // Handle or verify the server response if necessary.
            if (result) {
              $("#result").html("Login Successful!<br>" + result + "<br>Redirecting...");
              setTimeout(function() {
                window.location.href = "/catalog";
              }, 4000);
            } else if (authResult["error"]) {
              console.log("There was an error: " + authResult["error"]);
            } else {
              $("#result").html("Failed to make a server-side call. Check your configuration and console.");
            }
          }  
        }); 
      }
    }
  </script>
  <!--END GOOGLE PLUS SIGN IN -->

  <!--FACEBOOK SIGN IN -->
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '1549434938412095',
        cookie     : true,  // enable cookies to allow the server to access 
                            // the session
        xfbml      : true,  // parse social plugins on this page
        version    : 'v2.2' // use version 2.2
      });
    };

    // Load the SDK asynchronously
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    
    // Here we run a very simple test of the Graph API after login is
    // successful.  See statusChangeCallback() for when this call is made.
    function sendTokenToServer() {
      var access_token = FB.getAuthResponse()['accessToken'];
      console.log(access_token)
      console.log('Welcome!  Fetching your information.... ');
      FB.api('/me', function(response) {
        console.log('Successful login for: ' + response.name);
        $.ajax({
          type: 'POST',
          url: '/fbconnect?state={{STATE}}',
          processData: false,
          data: access_token,
          contentType: 'application/octet-stream; charset=utf-8',
          success: function(result) {
            // Handle or verify the server response if necessary.
            if (result) {
              $('#result').html('Login Successful!</br>'+ result + '</br>Redirecting...')
              setTimeout(function() {
                window.location.href = "/catalog";
              }, 4000);
            } else {
              $('#result').html('Failed to make a server-side call. Check your configuration and console.');
            }
          }   
        });
      });
    }
  </script>
  
  <button>
    <fb:login-button scope="public_profile,email" onlogin="sendTokenToServer();">
      <a href='javascript:sendTokenToServer()'>Login with Facebook</a>
    </fb:login-button>
  </button>
  <!--END FACEBOOK SIGN IN -->
  </body>
</html>

templates/new_item.html
{% extends "base.html" %}
{% block content %}
  <h2>Add Item</h2>
  
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 1rem;">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <div id="alert" class="alert alert-danger" role="alert" style="display: none;">
    <strong>Oups!</strong> Change a few things up and try submitting again.
  </div>

  <form name="myForm" action="{{url_for('item.new_item', category_name=category_name)}}" method="POST" onsubmit="return validateForm();">
    <div class="form-group">
      <label for="title">Title *</label>
      <input name="title" type="text" size="80" class="form-control" placeholder="Enter title">
      <small id="titleHelp" class="form-text text-danger" style="display: none;">This field marked by an asterisk must be filled out.</small>
    </div>

    <div class="form-group">
      <label for="description">Description *</label>
      <textarea name="description" class="form-control" rows="6" placeholder="Enter description"></textarea>
      <small id="descriptionHelp" class="form-text text-danger" style="display: none;">This field marked by an asterisk must be filled out.</small>
    </div>

    <div class="form-group" style="display: none;">
      <label for="category_name">Category</label>
      <input name="category_name" id="category_name" type="text" size="80" class="form-control" 
        {% if category_name %}
          value="{{category_name}}"
        {% endif %}>
    </div>

    <div class="input-group form-group" style="margin-bottom: 0">
      <div class="input-group-btn">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Category *
        </button>
        <div class="dropdown-menu" id="category_menu">
          {% for c in categories %}
            <a class="dropdown-item {% if c.name == category_name %}active{% endif %}" href="#">{{ c.name }}</a>
          {% endfor %}
        </div>
      </div>
      <input id="category_text" type="text" class="form-control" aria-label="Text input with dropdown button"
        {% if category_name %}
          value="{{category_name}}"
        {% endif %}>
    </div>

    <small id="categoryHelp" class="form-text text-danger" style="display: none;">This field marked by an asterisk must be filled out.</small>

    <p></p>
    
    <script>
      $(document).ready(function(){
        $('#category_menu a').click(function() {
          $("#category_menu a").removeClass("active")
          $(this).addClass('active'); 
          $("#category_text").val($(this).text())
          $("#category_name").val($(this).text())
        });

      });

      function validateForm() {
        var ok = true;

        var title = document.forms["myForm"]["title"].value;
        if (title == "") {
          ok = false;
          $("#titleHelp").show()
        } else {
          $("#titleHelp").hide()
        }
        
        var description = document.forms["myForm"]["description"].value;
        if (description == "") {
          ok = false;
          $("#descriptionHelp").show()
        } else {
          $("#descriptionHelp").hide()
        }
        
        var category_name = document.forms["myForm"]["category_name"].value;
        if (category_name == "") {
          ok = false;
          $("#categoryHelp").show()
        } else {
          $("#categoryHelp").hide()
        }

        if (!ok) {
          $("#alert").show()
        } else {
          $("#alert").hide()
        }

        return ok;
      }
    </script>

    {% if 'username' in session %}
      <div style="text-align: right;">
        <a href="{{url_for('category.show_categories')}}" class="btn btn-primary">Cancel</a>
        <input type="submit" value="Add" class="btn btn-danger">
      </div>
    {% endif %}
  </form>
{% endblock %}